[package]
name = "ndarray-simd"
version = "0.1.0"
authors = ["SparrowLii <liyuan179@huawei.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_arch = {path = "../stdarch-ndarray/crates/core_arch"}
